// flow-typed signature: 42cb18859da5d1b39e514268b7fb6390
// flow-typed version: <<STUB>>/react-flip-toolkit_v^7.0.12/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-flip-toolkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-flip-toolkit" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-flip-toolkit/lib/index.es" {
  declare module.exports: any
}

declare module "react-flip-toolkit/lib" {
  declare module.exports: any
}

declare module "react-flip-toolkit/lib/index.umd" {
  declare module.exports: any
}

// Filename aliases
declare module "react-flip-toolkit/lib/index.es.js" {
  declare module.exports: $Exports<"react-flip-toolkit/lib/index.es">
}
declare module "react-flip-toolkit/lib/index" {
  declare module.exports: $Exports<"react-flip-toolkit/lib">
}
declare module "react-flip-toolkit/lib/index.js" {
  declare module.exports: $Exports<"react-flip-toolkit/lib">
}
declare module "react-flip-toolkit/lib/index.umd.js" {
  declare module.exports: $Exports<"react-flip-toolkit/lib/index.umd">
}
